name = "servicego"
main = "src/index.ts"
compatibility_date = "2026-08-01"

# Melayani file frontend statis dari folder public
[assets]
directory = "./public"
binding = "ASSETS"

# Binding Database Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "servicego_db"
database_id = "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Ganti dengan ID dari 'wrangler d1 create servicego_db'
